### PR TITLE
JS app lint fixes

### PR DESCRIPTION
**Pull request by brgrz**
I had it with the annoying lint issues so this fixes most of them. Also code reformat did happen but you can always format it back to the way you want.

### CODE REVIEW

**Comment by tatarincev** [comment]
@brgrz Thanks, we'll check your changes

**Comment by tatarincev** [comment]
@Andrew-Orlov  Could you review this PR?

**Comment by Andrew-Orlov** [comment]
@tatarincev Sure.

**Comment by tatarincev** [comment]
@brgrz May I ask you re-create your PR into dev branch instead of master as you did?

**Comment by brgrz** [comment]
Done.

**Pull request closed without merging**
