### PR TITLE
Minificaton issues were added to description

### PR DESCRIPTION
**Pull request by kamilgarey**
These are the problems I came across and I mentioned it earlier.
[Now it looks](https://github.com/kamilgarey/vc-theme-default/tree/dev-minification-issues-were-add-to-description)

### CODE REVIEW

**Comment by eMazeika** [comment]
@kamilgarey was there a ticket, can you connect this PR to it?

**Comment by kamilgarey** [comment]
> @kamilgarey was there a ticket, can you connect this PR to it?

For first two issues there are no tickets. I don't think we should fix it at all. For the third ticket there is an issue it's linked in description. Should I connect this issue to PR?

**Comment by eMazeika** [comment]
> > @kamilgarey was there a ticket, can you connect this PR to it?
> 
> For first two issues there are no tickets. I don't think we should fix it at all. For the third ticket there is an issue it's linked in description. Should I connect this issue to PR?

not sure what is 1 and what's 2. Yes, connect ticket to PR

**Comment by kamilgarey** [comment]
I'm not sure should I connect while the commit not fix the issue but just mention it. Should  I?

**Pull request merged**
